# name: bsaAction

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: JDK 17을 설치합니다
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'adopt'

#       - name: Gradle 명령 실행을 위한 권한을 부여합니다
#         run: chmod +x gradlew

#       - name: Gradle build를 수행합니다
#         run: ./gradlew build

#       - name: 테스트 결과를 PR에 코멘트로 등록합니다
#         uses: EnricoMi/publish-unit-test-result-action@v1
#         if: always()
#         with:
#           files: '**/build/test-results/test/TEST-*.xml'

#       - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
#         uses: mikepenz/action-junit-report@v3
#         if: always()
#         with:
#           report_paths: '**/build/test-results/test/TEST-*.xml'
#           token: ${{ github.token }}
